language: rust
rust: stable
services: docker

env:
  global:
    - CRATE_NAME=wxwork_robotd
    - DISABLE_TESTS=1
    - RUST_BACKTRACE=1
    - LANG="zh_CN.UTF-8"
    - USING_CROSS=0
    - USING_TRUST=0
    - PKG_CONFIG_ALL_STATIC=1

matrix:
  include:
    # OSX
    #- os: osx
    #  env: USING_TRUST=1 TARGET=i686-apple-darwin
    - os: osx
      env: USING_SYSTEM_ALLOC=0 USING_CROSS=0 TARGET=x86_64-apple-darwin
    # ios
    # - env: USING_TRUST=1 TARGET=aarch64-apple-ios
    #   os: osx
    # - env: USING_TRUST=1 TARGET=armv7-apple-ios
    #   os: osx
    # - env: USING_TRUST=1 TARGET=armv7s-apple-ios
    #   os: osx
    # - env: USING_TRUST=1 TARGET=i386-apple-ios
    #   os: osx
    # - env: USING_TRUST=1 TARGET=x86_64-apple-ios
    #   os: osx
    # linux
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=1 USING_CROSS=1 TARGET=aarch64-unknown-linux-gnu
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=1 USING_CROSS=1 TARGET=arm-unknown-linux-gnueabi
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=1 USING_CROSS=1 TARGET=armv7-unknown-linux-gnueabihf
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=0 USING_CROSS=1 TARGET=i686-unknown-linux-gnu
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=mips-unknown-linux-gnu
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=mipsel-unknown-linux-gnu
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=mips64-unknown-linux-gnuabi64
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=mips64el-unknown-linux-gnuabi64
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=powerpc-unknown-linux-gnu
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=powerpc64-unknown-linux-gnu
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=powerpc64le-unknown-linux-gnu
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=0 USING_CROSS=0 TARGET=x86_64-unknown-linux-gnu
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=aarch64-unknown-linux-musl
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=arm-unknown-linux-musleabihf
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=arm-unknown-linux-musleabi
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=armv7-unknown-linux-musleabihf
    # linux-musl
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=0 USING_CROSS=1 TARGET=i686-unknown-linux-musl
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=mips-unknown-linux-musl
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_TRUST=1 TARGET=mipsel-unknown-linux-musl
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=0 USING_CROSS=1 TARGET=x86_64-unknown-linux-musl
    # Android
    - os: linux
      dist: xenial
      sudo: required
      env: USING_TRUST=1 TARGET=aarch64-linux-android
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=1 USING_CROSS=1 TARGET=arm-linux-androideabi  
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=1 USING_CROSS=1 TARGET=armv7-linux-androideabi
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=1 USING_CROSS=1 TARGET=i686-linux-android
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=1 USING_CROSS=1 TARGET=x86_64-linux-android
    # BSD
    - os: linux
      dist: xenial
      sudo: required
      env: USING_SYSTEM_ALLOC=0 USING_CROSS=1 TARGET=x86_64-unknown-netbsd
    # # Solaris
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   env: USING_SYSTEM_ALLOC=0 USING_CROSS=1 TARGET=x86_64-sun-solaris
    ## Windows
    # - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ulimit -a; sysctl -a; sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - rustup self update;
  - rustup update --force stable;
  - if [ $USING_TRUST -ne 0 ]; then

      set -e ;

    elif [ $USING_CROSS -ne 0 ]; then

      cargo install xargo --force;
      
      cargo install cross --force;

    else

      rustup target add $TARGET ;

      rustup toolchain install stable-$TARGET ;

    fi

install:
  - if [ $USING_TRUST -ne 0 ]; then

      bash ci/install.sh ;

      source ~/.cargo/env || true ;

    fi


script:
  - if [ $USING_SYSTEM_ALLOC -eq 0 ]; then 
    
      BUILD_WITH_SYSTEM_ALLOC="";

    else

      BUILD_WITH_SYSTEM_ALLOC=" --features system-alloc";

    fi
  - if [ $USING_TRUST -ne 0 ]; then

      bash ci/script.sh ;

    elif [ $USING_CROSS -ne 0 ]; then

      cross build --target $TARGET --release $BUILD_WITH_SYSTEM_ALLOC ;

    else

      env PKG_CONFIG_ALL_STATIC=1 cargo build --release --target $TARGET $BUILD_WITH_SYSTEM_ALLOC ;

    fi

    if [ -e "target/$TARGET/release/etc" ]; then

        rm -rf "target/$TARGET/release/etc";

    fi

    cp -rf etc "target/$TARGET/release"/ ;

    cd "target/$TARGET/release/";

    mkdir -p bin;

    if [ -e wxwork_robotd ]; then

      cp -f wxwork_robotd bin/wxwork_robotd;

    else

      cp -f wxwork_robotd* bin/;

    fi

    tar -zcvf $TARGET.tar.gz etc bin;

    cd ../../..;

    mv -f "target/$TARGET/release/$TARGET.tar.gz" ./;

cache: cargo

branches:
  only:
    - master

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name owt5008137
  - git config --local user.email "owt5008137@live.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: iNIX5yzdgFdldUWWQu5FfQZNdM2uVPtAt7Vv8Ugayvq0PHVrntTQXWvhOXR31nqC4h9X1Bjv+MyOzqnqk9A+rEvj2Ae1dUrkmSUSM0rIECOdMdem3UdJCN3ucILccQw2/NAr/c/WZxclByEEzVBKG35vT/c05wIIZ9fXOTCsknllcT77bN32TvnUbo53T5OG7ug/0hLEYaTGZncARSB2DtaSg8QP+dyyIAWrQpsMuoUJVSndW70vO7r5qi35ZvIX0Uw+y52vrWm0PN+EoDA4Cp0HT0ow2G4nzCs9133iuaz03/EgkoPoLboaVguiRcqq1TUAtUNoLmHSYGpw8vYRav7vQqYk+7D7D75Grv2PbzbhBxMRWvCRIpZm+0t6s4VOWhv1ByxFykWX4nJzsNNeeplxvqdLiFXo4V7RvBhJrC1Tf6ubPz6d+LkpoLWHcK1um2Hav48Fb83cIpVgDL1EqLV7yegXBunGvWuXLa1Ap0LfxvMi04h+2qBcoeenJOSdYo3LHJXk6n29w56MQPxp9aHw8uGY/8JF6i2dzm12QUrzcCjSDMQdtZqK226ovo+VKI5VT2Yq6r1BEZN/aF17B6hlhX6jKe12VVeBsKVuG2c8SQ3pth2vgTLg+UDZK9nZ+uTsWR8YO3KFQEqxIg3MY1GozrXrIrKdr3QbDN9UdYU=
  file: "*.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    repo: owt5008137/wxwork_robotd
    tags: true

notifications:
  email:
    recipients:
      - admin@owent.net
      - owt5008137@live.com
    on_success: never
    on_failure: never
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"