name: "Build On Linux"

on: [push]

jobs:
  build: # job id, can be any string
    # Job name is Build And Publish
    name: Build
    # This job runs on Linux
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        target:
          [
            aarch64-unknown-linux-gnu,
            arm-unknown-linux-gnueabi,
            armv7-unknown-linux-gnueabihf,
            i686-unknown-linux-gnu,
            x86_64-unknown-linux-gnu,
            i686-unknown-linux-musl,
            x86_64-unknown-linux-musl,
          ]
    runs-on: ${{ matrix.os }}
    env:
      VCPKGRS_DYNAMIC: 1
      OPENSSL_STATIC: 1
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          targets: x86_64-unknown-linux-gnu
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          if [ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]; then
            rustup target add ${{ matrix.target }} ;
            rustup toolchain install stable-${{ matrix.target }} ;
            env PKG_CONFIG_ALL_STATIC=1 cargo build --release --verbose --target ${{ matrix.target }} ;
          else
            cargo install xargo --force ;
            cargo install cross --force ;
            cross build --target ${{ matrix.target }} --release --verbose ;
          fi
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo test --verbose --target ${{ matrix.target }}
