name: "Build On Windows"

on: [push]

jobs:
  build: # job id, can be any string
    # Job name is Build And Publish
    name: Build
    # This job runs on Linux
    strategy:
      matrix:
        os: [windows-latest]
        rust: [stable]
        target:
          [
            x86_64-pc-windows-msvc,
            x86_64-pc-windows-gnu,
            i686-pc-windows-msvc,
            i686-pc-windows-gnu,
          ]
    runs-on: ${{ matrix.os }}
    env:
      VCPKGRS_DYNAMIC: 1
      OPENSSL_STATIC: 1
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install OpenSSL
        shell: bash
        run: |
          if [ "${{ matrix.target }}" == "i686-pc-windows-msvc" ] || [ "${{ matrix.target }}" == "i686-pc-windows-msvc" ]; then
            vcpkg install openssl --triplet x86-windows
            vcpkg install openssl --triplet x86-windows-static
          else
            vcpkg install openssl --triplet x64-windows
            vcpkg install openssl --triplet x64-windows-static
          fi
      - name: Build
        run: |
          cargo build --verbose --target ${{ matrix.target }}
      - name: Run tests
        run: |
          cargo test --verbose --target ${{ matrix.target }}
